# Flexiform configuration information for form mode displays.
core.entity_form_display.*.*.*.third_party.flexiform:
  type: mapping
  label: 'Flexiform Entity form display'
  mapping:
    enhancer:
      type: sequence
      label: 'Enhancer'
      sequence:
        type: flexiform.enhancer.[id]

flexiform.enhancer:
  type: mapping
  mapping:
    id:
      type: string
      label: 'ID'

flexiform.enhancer.*:
  type: flexiform.enhancer

flexiform.enhancer.multiple_entities:
  type: flexiform.enhancer
  label: 'Multiple entities'
  mapping:
    entities:
      type: sequence
      label: 'Entity'
      sequence:
        type: flexiform.form_entity.[plugin]

flexiform.enhancer.submit_button_ajax:
  type: flexiform.enhancer
  label: 'Submit button AJAX settings'
  mapping:
    ajax:
      type: sequence
      label: 'Ajax'
      sequence:
        type: mapping
        mapping:
          enabled:
            type: boolean
            label: 'Enabled'
          response:
            type: string
            label: 'Response action'

flexiform.enhancer.submit_button_label:
  type: flexiform.enhancer
  label: 'Submit button labels'
  mapping:
    label:
      type: sequence
      label: 'Label'
      sequence:
        type: string

flexiform.enhancer.submit_button_redirect:
  type: flexiform.enhancer
  label: 'Submit button redirect paths'
  mapping:
    redirect:
      type: sequence
      label: 'Redirect'
      sequence:
        type: path

flexiform.enhancer.page_exposure:
  type: flexiform.enhancer
  label: 'Page Exposure'

flexiform.form_entity:
  type: mapping
  mapping:
    label:
      type: string
      label: 'Entity label'
    plugin:
      type: string
      label: 'Entity plugin'
    save_on_submit:
      type: integer
      label: 'Save on submit'
    context_mapping:
      type: sequence
      label: 'Context assignments'
      sequence:
        - type: string

flexiform.form_entity.*:
  type: flexiform.form_entity

flexiform.form_entity.current_user:
  type: flexiform.form_entity
  label: 'Current User'

flexiform.form_entity.load:*:
  type: flexiform.form_entity
  label: 'Load Entity'
  mapping:
    id:
      type: string
      label: 'Entity id'

flexiform.form_entity.provided:*:
  type: flexiform.form_entity
  label: 'Provided Entity'

flexiform.form_entity.referenced_entity:*:*:*:*:
  type: flexiform.form_entity
  label: 'Referenced entity'
  mapping:
    create:
      type: boolean
      label: 'Create entity'
